"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from collections.abc import Sequence

if TYPE_CHECKING:
    ...
TYPE_PAIRS = ...
def normalize_upload_file_type(file_type: str | Sequence[str]) -> Sequence[str]:
    ...

def enforce_filename_restriction(filename: str, allowed_types: Sequence[str]) -> None:
    """Ensure the uploaded file's extension matches the allowed
    types set by the app developer. In theory, this should never happen, since we
    enforce file type check by extension on the frontend, but we check it on backend
    before returning file to the user to protect ourselves.
    """
    ...

