"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from authlib.integrations.base_client import FrameworkIntegration
from collections.abc import Sequence
from streamlit.web.server.oidc_mixin import TornadoOAuth

if TYPE_CHECKING:
    ...
class TornadoIntegration(FrameworkIntegration):
    def update_token(self, token: dict[str, Any], refresh_token: dict[str, Any] | None = ..., access_token: dict[str, Any] | None = ...) -> None:
        """We do not support access token refresh, since we obtain and operate only on
        identity tokens. We override this method explicitly to implement all abstract
        methods of base class.
        """
        ...
    
    @staticmethod
    def load_config(oauth: TornadoOAuth, name: str, params: Sequence[str]) -> dict[str, Any]:
        """Configure Authlib integration with provider parameters
        specified in secrets.toml.
        """
        ...
    


