"""
This type stub file was generated by pyright.
"""

import tornado.web
from typing import Any, Callable, TYPE_CHECKING
from authlib.integrations.base_client import BaseApp, BaseOAuth, OAuth2Mixin, OpenIDMixin
from streamlit.web.server.authlib_tornado_integration import TornadoIntegration
from streamlit.auth_util import AuthCache

if TYPE_CHECKING:
    ...
class TornadoOAuth2App(OAuth2Mixin, OpenIDMixin, BaseApp):
    client_cls = ...
    def load_server_metadata(self) -> dict[str, Any]:
        """We enforce S256 code challenge method if it is supported by the server."""
        ...
    
    def authorize_redirect(self, request_handler: tornado.web.RequestHandler, redirect_uri: Any = ..., **kwargs: Any) -> None:
        """Create a HTTP Redirect for Authorization Endpoint.

        :param request_handler: HTTP request instance from Tornado.
        :param redirect_uri: Callback or redirect URI for authorization.
        :param kwargs: Extra parameters to include.
        :return: A HTTP redirect response.
        """
        ...
    
    def authorize_access_token(self, request_handler: tornado.web.RequestHandler, **kwargs: Any) -> dict[str, Any]:
        """
        :param request_handler: HTTP request instance from Tornado.
        :return: A token dict.
        """
        ...
    


class TornadoOAuth(BaseOAuth):
    oauth2_client_cls = TornadoOAuth2App
    framework_integration_cls = TornadoIntegration
    def __init__(self, config: dict[str, Any] | None = ..., cache: AuthCache | None = ..., fetch_token: Callable[[dict[str, Any]], dict[str, Any]] | None = ..., update_token: Callable[[dict[str, Any]], dict[str, Any]] | None = ...) -> None:
        ...
    


