"""
This type stub file was generated by pyright.
"""

import tornado.web
from typing import TYPE_CHECKING
from streamlit.runtime.stats import StatsManager

if TYPE_CHECKING:
    ...
class StatsRequestHandler(tornado.web.RequestHandler):
    def initialize(self, stats_manager: StatsManager) -> None:
        ...
    
    def set_default_headers(self) -> None:
        ...
    
    def options(self) -> None:
        """/OPTIONS handler for preflight CORS checks."""
        ...
    
    def get(self) -> None:
        ...
    


