"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from streamlit.components.types.base_custom_component import BaseCustomComponent
from streamlit.errors import StreamlitAPIException
from streamlit.runtime.metrics_util import gather_metrics
from streamlit.runtime.state.common import WidgetCallback

if TYPE_CHECKING:
    ...
class MarshallComponentException(StreamlitAPIException):
    """Class for exceptions generated during custom component marshalling."""
    ...


class CustomComponent(BaseCustomComponent):
    """A Custom Component declaration."""
    def __call__(self, *args: Any, default: Any = ..., key: str | None = ..., on_change: WidgetCallback | None = ..., tab_index: int | None = ..., **kwargs: Any) -> Any:
        """An alias for create_instance."""
        ...
    
    @gather_metrics("create_instance")
    def create_instance(self, *args: Any, default: Any = ..., key: str | None = ..., on_change: WidgetCallback | None = ..., tab_index: int | None = ..., **kwargs: Any) -> Any:
        """Create a new instance of the component.

        Parameters
        ----------
        *args
            Must be empty; all args must be named. (This parameter exists to
            enforce correct use of the function.)
        default: any or None
            The default return value for the component. This is returned when
            the component's frontend hasn't yet specified a value with
            `setComponentValue`.
        key: str or None
            If not None, this is the user key we use to generate the
            component's "widget ID".
        on_change: WidgetCallback or None
            An optional callback invoked when the widget's value changes. No arguments are passed to it.
        tab_index : int, optional
            Specifies the tab order of the iframe containing the component.
            Possible values are:
            - ``None`` (default): Browser default behavior.
            - ``-1``: Removes the iframe from the natural tab order, but it can still be focused programmatically.
            - ``0`` or positive integer: Includes the iframe in the natural tab order.
        **kwargs
            Keyword args to pass to the component.

        Returns
        -------
        any or None
            The component's widget value.

        """
        ...
    
    def __eq__(self, other: object) -> bool:
        """Equality operator."""
        ...
    
    __hash__ = ...
    def __ne__(self, other: object) -> bool:
        """Inequality operator."""
        ...
    
    def __str__(self) -> str:
        ...
    


