"""
This type stub file was generated by pyright.
"""

from streamlit.connections.base_connection import BaseConnection
from streamlit.connections.snowflake_connection import SnowflakeConnection
from streamlit.connections.snowpark_connection import SnowparkConnection
from streamlit.connections.sql_connection import SQLConnection

ExperimentalBaseConnection = BaseConnection
__all__ = ["BaseConnection", "ExperimentalBaseConnection", "SQLConnection", "SnowflakeConnection", "SnowparkConnection"]
