"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from collections.abc import Collection

if TYPE_CHECKING:
    ...
SNOWSQL_CONNECTION_FILE = ...
def extract_from_dict(keys: Collection[str], source_dict: dict[str, Any]) -> dict[str, Any]:
    """Extract the specified keys from source_dict and return them in a new dict.

    Parameters
    ----------
    keys : Collection[str]
        The keys to extract from source_dict.
    source_dict : Dict[str, Any]
        The dict to extract keys from. Note that this function mutates source_dict.

    Returns
    -------
    Dict[str, Any]
        A new dict containing the keys/values extracted from source_dict.
    """
    ...

def load_from_snowsql_config_file(connection_name: str) -> dict[str, Any]:
    """Loads the dictionary from snowsql config file."""
    ...

def running_in_sis() -> bool:
    """Return whether this app is running in SiS."""
    ...

