"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from streamlit.runtime.metrics_util import gather_metrics
from streamlit.delta_generator import DeltaGenerator

if TYPE_CHECKING:
    ...
class SnowMixin:
    @gather_metrics("snow")
    def snow(self) -> DeltaGenerator:
        """Draw celebratory snowfall.

        Example
        -------
        >>> import streamlit as st
        >>>
        >>> st.snow()

        ...then watch your app and get ready for a cool celebration!

        """
        ...
    
    @property
    def dg(self) -> DeltaGenerator:
        """Get our DeltaGenerator."""
        ...
    


