"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from streamlit.runtime.caching.storage import CacheStorageManager

if TYPE_CHECKING:
    ...
def create_default_cache_storage_manager() -> CacheStorageManager:
    """
    Get the cache storage manager.
    It would be used both in server.py and in cli.py to have unified cache storage.

    Returns
    -------
    CacheStorageManager
        The cache storage manager.

    """
    ...

