"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from streamlit.runtime.pages_manager import PagesManager

if TYPE_CHECKING:
    ...
def maybe_trim_page_path(url: str, page_manager: PagesManager) -> str:
    """Trim the page path from the URL if it exists."""
    ...

def maybe_add_page_path(url: str, page_manager: PagesManager) -> str:
    """Add the page path to the URL if it exists."""
    ...

