"""
This type stub file was generated by pyright.
"""

from streamlit.config_option import ConfigOption

def server_option_changed(old_options: dict[str, ConfigOption], new_options: dict[str, ConfigOption]) -> bool:
    """Return True if and only if an option in the server section differs
    between old_options and new_options.
    """
    ...

def show_config(section_descriptions: dict[str, str], config_options: dict[str, ConfigOption]) -> None:
    """Print the given config sections/options to the terminal."""
    ...

