"""
This type stub file was generated by pyright.
"""

SYSTEM = ...
IS_WINDOWS = ...
IS_DARWIN = ...
IS_LINUX_OR_BSD = ...
def is_pex() -> bool:
    """Return if streamlit running in pex.

    Pex modifies sys.path so the pex file is the first path and that's
    how we determine we're running in the pex file.
    """
    ...

def is_repl() -> bool:
    """Return True if running in the Python REPL."""
    ...

def is_executable_in_path(name: str) -> bool:
    """Check if executable is in OS path."""
    ...

