"""
This type stub file was generated by pyright.
"""

from typing import Final

_LOGGER: Final = ...
def handle_uncaught_app_exception(ex: BaseException) -> None:
    """Handle an exception that originated from a user app.

    By default, we show exceptions directly in the browser. However,
    if the user has disabled client error details, we display a generic
    warning in the frontend instead.
    """
    ...

