"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from git import Commit, Remote, RemoteReference, Repo

if TYPE_CHECKING:
    ...
GITHUB_HTTP_URL = ...
GITHUB_SSH_URL = ...
MIN_GIT_VERSION = ...
class GitRepo:
    repo: Repo | None
    def __init__(self, path: str) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def is_valid(self) -> bool:
        """True if there's a git repo here, and git.version >= MIN_GIT_VERSION."""
        ...
    
    @property
    def tracking_branch(self) -> RemoteReference | None:
        ...
    
    @property
    def untracked_files(self) -> list[str] | None:
        ...
    
    @property
    def is_head_detached(self) -> bool:
        ...
    
    @property
    def uncommitted_files(self) -> list[str] | None:
        ...
    
    @property
    def ahead_commits(self) -> list[Commit] | None:
        ...
    
    def get_tracking_branch_remote(self) -> tuple[Remote, str] | None:
        ...
    
    def is_github_repo(self) -> bool:
        ...
    
    def get_repo_info(self) -> tuple[str, str, str] | None:
        ...
    


