"""
This type stub file was generated by pyright.
"""

import logging
from typing import Final

"""Logging module."""
DEFAULT_LOG_MESSAGE: Final = ...
_loggers: dict[str, logging.Logger] = ...
_global_log_level = ...
def set_log_level(level: str | int) -> None:
    """Set log level."""
    ...

def setup_formatter(logger: logging.Logger) -> None:
    """Set up the console formatter for a given logger."""
    ...

def update_formatter() -> None:
    ...

def init_tornado_logs() -> None:
    """Set Tornado log levels.

    This function does not import any Tornado code, so it's safe to call even
    when Server is not running.
    """
    ...

def get_logger(name: str) -> logging.Logger:
    """Return a logger.

    Parameters
    ----------
    name : str
        The name of the logger to use. You should just pass in __name__.

    Returns
    -------
    Logger

    """
    ...

