"""
This type stub file was generated by pyright.
"""

"""A generated list with all valid material symbols names.

DO NOT EDIT MANUALLY! The list in this file is generated by `scripts/update_material_icon_names.py`.

This module gets lazy-loaded only when a material icon name check is required.
"""
ALL_MATERIAL_ICONS = ...
