"""
This type stub file was generated by pyright.
"""

"""Platform module."""
def post_parent_message(message: str) -> None:
    """Sends a string message to the parent window (when host configuration allows)."""
    ...

