"""
This type stub file was generated by pyright.
"""

from typing import Final, TYPE_CHECKING
from streamlit.type_util import SupportsStr

if TYPE_CHECKING:
    ...
_ALPHANUMERIC_CHAR_REGEX: Final = ...
def clean_text(text: SupportsStr) -> str:
    """Convert an object to text, dedent it, and strip whitespace."""
    ...

def is_emoji(text: str) -> bool:
    """Check if input string is a valid emoji."""
    ...

def is_material_icon(maybe_icon: str) -> bool:
    """Check if input string is a valid Material icon."""
    ...

def validate_icon_or_emoji(icon: str | None) -> str:
    """Validate an icon or emoji and return it in normalized format if valid."""
    ...

def validate_emoji(maybe_emoji: str | None) -> str:
    ...

def validate_material_icon(maybe_material_icon: str | None) -> str:
    """Validate a Material icon shortcode and return the icon in
    normalized format if valid.
    """
    ...

def extract_leading_emoji(text: str) -> tuple[str, str]:
    """Return a tuple containing the first emoji found in the given string and
    the rest of the string (minus an optional separator between the two).
    """
    ...

def max_char_sequence(string: str, char: str) -> int:
    """Returns the count of the max sequence of a given char in a string."""
    ...

TEXTCHARS: Final = ...
def is_binary_string(inp: bytes) -> bool:
    """Guess if an input bytesarray can be encoded as a string."""
    ...

def simplify_number(num: int) -> str:
    """Simplifies number into Human readable format, returns str."""
    ...

_OBJ_MEM_ADDRESS: Final = ...
def is_mem_address_str(string: str) -> bool:
    """Returns True if the string looks like <foo blarg at 0x15ee6f9a0>."""
    ...

def to_snake_case(camel_case_str: str) -> str:
    """Converts UpperCamelCase and lowerCamelCase to snake_case.

    Examples
    --------
        fooBar -> foo_bar
        BazBang -> baz_bang

    """
    ...

