"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from types import TracebackType

if TYPE_CHECKING:
    ...
class TemporaryDirectory:
    """Temporary directory context manager.

    Creates a temporary directory that exists within the context manager scope.
    It returns the path to the created directory.
    Wrapper on top of tempfile.mkdtemp.

    Parameters
    ----------
    suffix : str or None
        Suffix to the filename.
    prefix : str or None
        Prefix to the filename.
    dir : str or None
        Enclosing directory.

    """
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __enter__(self) -> str:
        ...
    
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, exc_traceback: TracebackType | None) -> None:
        ...
    


