"""
This type stub file was generated by pyright.
"""

from datetime import date, timedelta
from typing import Literal, overload

def adjust_years(input_date: date, years: int) -> date:
    """Add or subtract years from a date."""
    ...

@overload
def time_to_seconds(t: float | timedelta | str | None, *, coerce_none_to_inf: Literal[False]) -> float | None:
    ...

@overload
def time_to_seconds(t: float | timedelta | str | None) -> float:
    ...

def time_to_seconds(t: float | timedelta | str | None, *, coerce_none_to_inf: bool = ...) -> float | None:
    """Convert a time string value to a float representing "number of seconds"."""
    ...

