"""
This type stub file was generated by pyright.
"""

from streamlit.runtime.state.common import WidgetArgs, WidgetCallback, WidgetKwargs
from streamlit.runtime.state.query_params_proxy import QueryParamsProxy
from streamlit.runtime.state.safe_session_state import SafeSessionState
from streamlit.runtime.state.session_state import SCRIPT_RUN_WITHOUT_ERRORS_KEY, SessionState, SessionStateStatProvider
from streamlit.runtime.state.session_state_proxy import SessionStateProxy, get_session_state
from streamlit.runtime.state.widgets import register_widget

__all__ = ["SCRIPT_RUN_WITHOUT_ERRORS_KEY", "QueryParamsProxy", "SafeSessionState", "SessionState", "SessionStateProxy", "SessionStateStatProvider", "WidgetArgs", "WidgetCallback", "WidgetKwargs", "get_session_state", "register_widget"]
