"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Final, NamedTuple, TYPE_CHECKING
from streamlit.watcher.path_watcher import PathWatcherType
from types import ModuleType
from streamlit.runtime.pages_manager import PagesManager

if TYPE_CHECKING:
    ...
_LOGGER: Final = ...
class WatchedModule(NamedTuple):
    watcher: Any
    module_name: str | None
    ...


PathWatcher: PathWatcherType | None = ...
class LocalSourcesWatcher:
    def __init__(self, pages_manager: PagesManager) -> None:
        ...
    
    def update_watched_pages(self) -> None:
        ...
    
    def register_file_change_callback(self, cb: Callable[[str], None]) -> None:
        ...
    
    def on_path_changed(self, filepath: str) -> None:
        ...
    
    def close(self) -> None:
        ...
    
    def update_watched_modules(self) -> None:
        ...
    


def get_module_paths(module: ModuleType) -> set[str]:
    ...

