"""
This type stub file was generated by pyright.
"""

from typing import Callable, Final

"""A class that watches a given path via polling."""
_LOGGER: Final = ...
_MAX_WORKERS: Final = ...
_POLLING_PERIOD_SECS: Final = ...
class PollingPathWatcher:
    """Watches a path on disk via a polling loop."""
    _executor = ...
    @staticmethod
    def close_all() -> None:
        """Close top-level watcher object.

        This is a no-op, and exists for interface parity with
        EventBasedPathWatcher.
        """
        ...
    
    def __init__(self, path: str, on_changed: Callable[[str], None], *, glob_pattern: str | None = ..., allow_nonexistent: bool = ...) -> None:
        """Constructor.

        You do not need to retain a reference to a PollingPathWatcher to
        prevent it from being garbage collected. (The global _executor object
        retains references to all active instances.)
        """
        ...
    
    def __repr__(self) -> str:
        ...
    
    def close(self) -> None:
        """Stop watching the file system."""
        ...
    


