"""
This type stub file was generated by pyright.
"""

from streamlit.runtime.caching.storage.cache_storage_protocol import CacheStorage, CacheStorageContext, CacheStorageManager

class MemoryCacheStorageManager(CacheStorageManager):
    def create(self, context: CacheStorageContext) -> CacheStorage:
        """Creates a new cache storage instance wrapped with in-memory cache layer."""
        ...
    
    def clear_all(self) -> None:
        ...
    
    def check_context(self, context: CacheStorageContext) -> None:
        ...
    


class DummyCacheStorage(CacheStorage):
    def get(self, key: str) -> bytes:
        """
        Dummy gets the value for a given key,
        always raises an CacheStorageKeyNotFoundError.
        """
        ...
    
    def set(self, key: str, value: bytes) -> None:
        ...
    
    def delete(self, key: str) -> None:
        ...
    
    def clear(self) -> None:
        ...
    
    def close(self) -> None:
        ...
    


