"""
This type stub file was generated by pyright.
"""

from typing import Final, TYPE_CHECKING
from streamlit.components.types.base_component_registry import BaseComponentRegistry
from streamlit.components.types.base_custom_component import BaseCustomComponent

if TYPE_CHECKING:
    ...
_LOGGER: Final = ...
class LocalComponentRegistry(BaseComponentRegistry):
    def __init__(self) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def register_component(self, component: BaseCustomComponent) -> None:
        """Register a CustomComponent.

        Parameters
        ----------
        component : BaseCustomComponent
            The component to register.
        """
        ...
    
    def get_component_path(self, name: str) -> str | None:
        """Return the filesystem path for the component with the given name.

        If no such component is registered, or if the component exists but is
        being served from a URL, return None instead.
        """
        ...
    
    def get_module_name(self, name: str) -> str | None:
        ...
    
    def get_component(self, name: str) -> BaseCustomComponent | None:
        ...
    
    def get_components(self) -> list[BaseCustomComponent]:
        ...
    


