# stubs/MetaTrader5/__init__.pyi
from typing import NamedTuple

class Tick(NamedTuple):
    time: int
    bid: float
    ask: float

class AccountInfo(NamedTuple):
    login: int
    server: str

class TerminalInfo(NamedTuple):
    community_account: str
    community_connection: bool

def initialize(path: str | None = ...) -> bool: ...
def shutdown() -> None: ...
def login(login: int | str, password: str, server: str) -> bool: ...
def last_error() -> tuple[int, str]: ...
def version() -> tuple[int, int, int, int]: ...
def symbol_select(symbol: str, enable: bool = ...) -> bool: ...
def symbol_info_tick(symbol: str) -> Tick | None: ...
def account_info() -> AccountInfo | None: ...
def terminal_info() -> TerminalInfo | None: ...
