"""
This type stub file was generated by pyright.
"""

from typing import Any, Final

MAGIC_MODULE_NAME: Final = ...
def add_magic(code: str, script_path: str) -> Any:
    """Modifies the code to support magic Streamlit commands.

    Parameters
    ----------
    code : str
        The Python code.
    script_path : str
        The path to the script file.

    Returns
    -------
    ast.Module
        The syntax tree for the code.

    """
    ...

